/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_pkg;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Apex
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signin_head = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        numsigin = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        namesigin = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();
        emailsigin = new javax.swing.JTextField();
        username3 = new javax.swing.JLabel();
        javax.swing.JButton sigin_cancel_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JButton Signin_btn1 = new javax.swing.JButton();
        pwdsignin = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        pwd1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(null);

        signin_head.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        signin_head.setForeground(new java.awt.Color(0, 0, 255));
        signin_head.setText("Sign up");
        jPanel1.add(signin_head);
        signin_head.setBounds(30, 70, 120, 42);

        username.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        username.setText("Enter name");
        jPanel1.add(username);
        username.setBounds(30, 120, 183, 20);

        numsigin.setBackground(new java.awt.Color(204, 204, 204));
        numsigin.setForeground(new java.awt.Color(51, 0, 255));
        numsigin.setBorder(null);
        numsigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numsiginActionPerformed(evt);
            }
        });
        jPanel1.add(numsigin);
        numsigin.setBounds(30, 200, 229, 28);

        username1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        username1.setText("Enter mobile number");
        jPanel1.add(username1);
        username1.setBounds(30, 180, 183, 20);

        namesigin.setBackground(new java.awt.Color(204, 204, 204));
        namesigin.setForeground(new java.awt.Color(51, 0, 255));
        namesigin.setActionCommand("oakyyyy");
        namesigin.setBorder(null);
        namesigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesiginActionPerformed(evt);
            }
        });
        jPanel1.add(namesigin);
        namesigin.setBounds(30, 140, 229, 28);

        username2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        username2.setText("Enter email");
        jPanel1.add(username2);
        username2.setBounds(30, 240, 183, 20);

        emailsigin.setBackground(new java.awt.Color(204, 204, 204));
        emailsigin.setForeground(new java.awt.Color(51, 0, 255));
        emailsigin.setBorder(null);
        emailsigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailsiginActionPerformed(evt);
            }
        });
        jPanel1.add(emailsigin);
        emailsigin.setBounds(30, 260, 229, 28);

        username3.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        username3.setText("Enter password");
        jPanel1.add(username3);
        username3.setBounds(30, 300, 183, 20);

        sigin_cancel_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sigin_cancel_btn.setText("Cancel");
        sigin_cancel_btn.setMargin(new java.awt.Insets(5, 5, 5, 5));
        sigin_cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigin_cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sigin_cancel_btn);
        sigin_cancel_btn.setBounds(160, 390, 99, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_pkg/index_3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(273, 103, 470, 399);

        Signin_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Signin_btn1.setText("Sign up");
        Signin_btn1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        Signin_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signin_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Signin_btn1);
        Signin_btn1.setBounds(30, 390, 99, 28);

        pwdsignin.setBackground(new java.awt.Color(204, 204, 204));
        pwdsignin.setForeground(new java.awt.Color(0, 0, 255));
        pwdsignin.setBorder(null);
        pwdsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdsigninActionPerformed(evt);
            }
        });
        jPanel1.add(pwdsignin);
        pwdsignin.setBounds(30, 320, 229, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_pkg/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 10, 190, 40);

        pwd1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        pwd1.setForeground(new java.awt.Color(0, 0, 255));
        pwd1.setText("sign-in with exiting account");
        pwd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pwd1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pwd1.setDoubleBuffered(true);
        pwd1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pwd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwd1MouseClicked(evt);
            }
        });
        jPanel1.add(pwd1);
        pwd1.setBounds(70, 360, 160, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numsiginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numsiginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numsiginActionPerformed

    private void namesiginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesiginActionPerformed

    }//GEN-LAST:event_namesiginActionPerformed

    private void emailsiginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailsiginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailsiginActionPerformed

    private void sigin_cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigin_cancel_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sigin_cancel_btnActionPerformed

    private void pwdsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdsigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdsigninActionPerformed

    private void pwd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwd1MouseClicked
        //System.exit(0);
        Login obj = new Login();
        this.setState(JFrame.ICONIFIED);    //for close old window
        obj.setVisible(true);
        obj.setTitle("Login");

    }//GEN-LAST:event_pwd1MouseClicked

    private void Signin_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signin_btn1ActionPerformed
            Con2 objCon2 = new Con2();
        try {
            objCon2.getCon();
            objCon2.signup();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_Signin_btn1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField emailsigin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField namesigin;
    public static javax.swing.JTextField numsigin;
    private javax.swing.JLabel pwd1;
    public static javax.swing.JPasswordField pwdsignin;
    private javax.swing.JLabel signin_head;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new Signup().setVisible(true);
        }
    }
}
